const $ = (s, root = document) => root.querySelector(s);
const state = { file: null, text: "", result: null, config: JSON.parse(localStorage.getItem("medsight-api-config") || "{}"), projects: JSON.parse(localStorage.getItem("medsight-projects") || "[]"), activeProjectId: localStorage.getItem("medsight-active-project") || null };
const dropzone = $("#dropzone"), input = $("#file-input"), fileRow = $("#file-row"), analyzeButton = $("#analyze-button"), status = $("#status"), progress = $("#progress");
const setIcons = () => window.lucide?.createIcons();
const projectModal=$("#projects-modal");
async function api(path, options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`请求失败 ${r.status}`);return r.status===204?null:r.json()}
function saveProjects(){localStorage.setItem("medsight-projects",JSON.stringify(state.projects));if(state.activeProjectId)localStorage.setItem("medsight-active-project",state.activeProjectId)}
async function loadProjects(){try{const d=await api("/api/projects");state.projects=d.projects||[];if(!state.activeProjectId||!state.projects.some(p=>p.id===state.activeProjectId))state.activeProjectId=state.projects[0]?.id||null;saveProjects();}catch(e){console.warn("项目列表加载失败",e)}}
async function openFileResult(name){const m=$("#file-result-modal");m.classList.add("open");$("#file-result-title").textContent=name;try{const d=await api(`/api/projects/${state.activeProjectId}/files/${encodeURIComponent(name)}`);$("#file-result-status").textContent=d.file.status||"Pending";$("#file-result-content").textContent=JSON.stringify(d.parsed||{message:"No parsed result yet",file:d.file},null,2);$("#retry-file").onclick=async()=>{await api(`/api/projects/${state.activeProjectId}/files/${encodeURIComponent(name)}/retry`,{method:"POST"});await loadProjects();renderFiles();$("#file-result-status").textContent="Processing"}}catch(e){$("#file-result-status").textContent="Failed: "+e.message}}
function renderFiles(){const list=$("#file-list");if(!list)return;const project=state.projects.find(item=>item.id===state.activeProjectId);const filter=$("#file-filter")?.value||"all";const files=(project?.files||[]).filter(file=>filter==="all"||file.kind===filter);list.innerHTML=files.length?files.map(file=>`<div class="file-item"><strong>${escapeHtml(file.name)}</strong><small>${escapeHtml(file.kind)} · ${file.status||"Pending"} · ${new Date(file.uploadedAt||Date.now()).toLocaleString()}</small><button class="delete-file" data-name="${escapeHtml(file.name)}" type="button">Delete</button></div>`).join(""):"<div class=project-empty>No files</div>"}
function openPreview(name){const modal=$("#preview-modal"),frame=$("#preview-frame"),title=$("#preview-title");if(!modal||!frame)return;title.textContent=name;frame.src=`/api/projects/${state.activeProjectId}/files/${encodeURIComponent(name)}/raw`;modal.classList.add("open")}
async function selectUploadedFile(name){const project=state.projects.find(item=>item.id===state.activeProjectId);const meta=project?.files?.find(file=>file.name===name);if(!meta)return;try{const response=await fetch(`/api/projects/${state.activeProjectId}/files/${encodeURIComponent(name)}/raw`);if(!response.ok)throw new Error("Unable to load file");const blob=await response.blob();setFile(new File([blob],meta.name,{type:blob.type||"application/pdf"}));showStatus("File selected. Ready to analyze")}catch(error){showStatus(error.message,true)}}
function renderUploadedFiles(){const list=$("#uploaded-files");if(!list)return;const project=state.projects.find(item=>item.id===state.activeProjectId);const files=project?.files||[],pdfs=files.filter(file=>file.kind==="pdfs"),processing=project?.status==="处理中";list.innerHTML=files.length?files.map(file=>`<div class="uploaded-file"><i data-lucide="${file.kind==="pdfs"?"file-text":"image"}"></i><button class="uploaded-select" data-name="${escapeHtml(file.name)}" type="button"><strong title="${escapeHtml(file.name)}">${escapeHtml(file.name)}</strong><small>${file.status||"待解析"}</small></button><button class="uploaded-preview" data-name="${escapeHtml(file.name)}" type="button" title="预览"><i data-lucide="eye"></i></button><button class="uploaded-delete" data-name="${escapeHtml(file.name)}" type="button" title="删除"><i data-lucide="trash-2"></i></button></div>`).join(""):"";const badge=$("#current-project");if(badge)badge.textContent=project?project.name:"未选择项目";analyzeButton.disabled=!pdfs.length||processing;analyzeButton.querySelector("span").innerHTML=`<i data-lucide="${processing?"loader-circle":"sparkles"}"></i>${processing?"正在分析项目":"分析全部报告"}`;if(project?.analysisSummary&&!processing)render(project.analysisSummary);setIcons()}
$("#uploaded-files")?.addEventListener("click",async event=>{const select=event.target.closest(".uploaded-select"),preview=event.target.closest(".uploaded-preview"),remove=event.target.closest(".uploaded-delete");if(select){await selectUploadedFile(select.dataset.name)}if(preview){openPreview(preview.dataset.name)}if(remove){if(confirm("Delete this file?")){await api(`/api/projects/${state.activeProjectId}/files/${encodeURIComponent(remove.dataset.name)}`,{method:"DELETE"});await loadProjects();renderUploadedFiles();showStatus("File deleted")}}});
function renderProjects(){const q=$("#project-search").value.trim().toLowerCase(),list=$("#project-list"),rows=state.projects.filter(p=>!q||`${p.name} ${p.patientName||""}`.toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(p=>`<div class="project-item ${p.id===state.activeProjectId?'active':''}" data-id="${p.id}"><span class="project-icon"><i data-lucide="folder"></i></span><div class="project-main"><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.patientName||"No patient")} · ${escapeHtml(p.status)} · ${(p.files||[]).length} files · ${new Date(p.updatedAt).toLocaleString()}</small></div><div class="project-actions"><button class="small-button open-project" data-id="${p.id}" type="button">Open</button><button class="icon-button delete-project" data-id="${p.id}" type="button"><i data-lucide="trash-2"></i></button></div></div>`).join(""): '<div class="project-empty">No projects yet</div>';renderFiles();renderUploadedFiles();setIcons()}
async function openProjects(){await loadProjects();renderProjects();projectModal.classList.add("open")};function closeProjects(){projectModal.classList.remove("open")};async function createProject(){const i=$("#project-name"),name=i.value.trim();if(!name)return i.focus();try{const p=await api("/api/projects",{method:"POST",body:JSON.stringify({name})});state.projects.unshift(p);state.activeProjectId=p.id;saveProjects();i.value="";renderProjects();showStatus(`已创建项目：${name}`)}catch(e){showStatus(e.message,true)}}
$("#projects-button")?.addEventListener("click",openProjects);$("#close-projects")?.addEventListener("click",closeProjects);$("#create-project")?.addEventListener("click",createProject);$("#project-name")?.addEventListener("keydown",e=>{if(e.key==="Enter")createProject()});$("#project-search")?.addEventListener("input",renderProjects);$("#file-filter")?.addEventListener("change",renderFiles);$("#project-list")?.addEventListener("click",async e=>{const id=e.target.closest("[data-id]")?.dataset.id;if(!id)return;if(e.target.closest(".delete-project")){if(confirm("Delete this project?")){await api(`/api/projects/${id}`,{method:"DELETE"});state.projects=state.projects.filter(p=>p.id!==id);saveProjects();renderProjects();showStatus("Project deleted")}}else if(e.target.closest(".open-project")){state.activeProjectId=id;saveProjects();renderProjects();closeProjects();showStatus("Project opened")}});$("#file-list")?.addEventListener("click",async e=>{const b=e.target.closest(".delete-file"),row=e.target.closest(".file-item");if(!state.activeProjectId)return;if(b){if(confirm("Delete this file?")){await api(`/api/projects/${state.activeProjectId}/files/${b.dataset.name}`,{method:"DELETE"});await loadProjects();renderFiles();showStatus("File deleted")}}else if(row)openFileResult(row.querySelector("strong").textContent)});$("#close-file-result")?.addEventListener("click",()=>$("#file-result-modal").classList.remove("open")); loadProjects().then(()=>openProjects());

function setFile(file) {
  if (!file) return;
  if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) return showStatus("请选择 PDF 文件", true);
  if (file.size > 20 * 1024 * 1024) return showStatus("文件超过 20 MB，请压缩后重试", true);
  state.file = file; fileRow.classList.remove("empty"); $("#file-name").textContent = file.name; $("#file-meta").textContent = `${(file.size / 1024 / 1024).toFixed(2)} MB · PDF`;
  analyzeButton.disabled = false; showStatus("文件已就绪，可以开始分析"); setIcons();
}
async function uploadFiles(files){const projectId=state.activeProjectId;if(!projectId){showStatus("Open or create a project first",true);await openProjects();return}const selected=Array.from(files||[]);if(!selected.length)return;let uploaded=0;for(const file of selected){if(file.size>20*1024*1024){showStatus(`${file.name} exceeds 20 MB`,true);continue}const isPdf=file.name.toLowerCase().endsWith(".pdf");if(!isPdf&&!/^image\/(png|jpeg|jpg)$/.test(file.type)){showStatus(`Unsupported file: ${file.name}`,true);continue}showStatus(`Uploading ${file.name}…`);try{const base64=await toBase64(file);await api(`/api/projects/${projectId}/upload`,{method:"POST",body:JSON.stringify({name:file.name,size:file.size,kind:isPdf?"pdf":"screenshot",base64})});uploaded++;if(isPdf&&!state.file)setFile(file)}catch(error){showStatus(`${file.name} upload failed: ${error.message}`,true)}}await loadProjects();renderFiles();renderUploadedFiles();input.value="";showStatus(uploaded?`${uploaded} file(s) uploaded to the current project`:"No files uploaded",uploaded===0)}
function showStatus(message, error = false) { status.textContent = message; status.classList.toggle("error", error); }
function resetFile() { state.file = null; state.text = ""; input.value = ""; fileRow.classList.add("empty"); $("#file-name").textContent = "尚未选择文件"; $("#file-meta").textContent = "PDF 文件将在此显示"; analyzeButton.disabled = true; showStatus("等待上传报告"); }
async function extractText(file) {
  const pdfjs = globalThis.pdfjsLib;
  if (!pdfjs) return "";
  pdfjs.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
  const pdf = await pdfjs.getDocument({ data: await file.arrayBuffer() }).promise; let text = "";
  for (let pageNo = 1; pageNo <= pdf.numPages; pageNo++) { const page = await pdf.getPage(pageNo); const content = await page.getTextContent(); text += content.items.map(item => item.str).join(" ") + "\n"; }
  return text.trim();
}
const first = (re, text, fallback = "未识别") => (text.match(re)?.[1] || fallback).trim();
function analyze(text, file) {
  const values = []; const pattern = /([\u4e00-\u9fa5A-Za-z（）()]{2,18})\s*[:：]?\s*([<>≤≥]?\s*\d+(?:\.\d+)?)\s*(mg\/L|g\/L|mmol\/L|μmol\/L|U\/L|%|次\/分|mmHg)?\s*(?:参考范围|参考值)?\s*[:：]?\s*([\d.]+\s*[-~至]\s*[\d.]+)/gi;
  let match; while ((match = pattern.exec(text)) && values.length < 8) values.push({ name: match[1], value: match[2] + (match[3] ? ` ${match[3]}` : ""), ref: match[4] || "报告原文未提供" });
  const abnormalWords = /(异常|偏高|偏低|阳性|可疑|增厚|结节|炎症|占位|未见|风险|超出|升高|降低)/; const findings = [];
  const sentences = text.split(/[。.!！\n]/).map(s => s.trim()).filter(Boolean);
  sentences.filter(s => abnormalWords.test(s)).slice(0, 5).forEach((s, i) => findings.push({ title: i === 0 ? "报告中出现需要关注的描述" : "原文提示", detail: s.slice(0, 150), high: /(阳性|占位|可疑|结节|风险)/.test(s) }));
  const diagnosis = first(/(?:诊断|检查结论|影像学表现|印象)\s*[:：]?\s*([^\n。]{4,100})/, text);
  const date = first(/(20\d{2}[年\/-]\d{1,2}[月\/-]\d{1,2}日?)/, text);
  const summary = diagnosis !== "未识别" ? `报告主要结论为“${diagnosis}”。系统整理出 ${values.length || "若干"} 个可读字段${findings.length ? `，其中 ${findings.length} 处文字需要和医生进一步确认` : "，未在文本中发现明显的风险关键词"}。` : `已读取《${file.name}》并完成初步整理。报告中包含 ${values.length || "若干"} 个可识别字段，建议结合原始影像和医生解读确认结论。`;
  const fields = [{ label: "报告文件", value: file.name }, { label: "检查日期", value: date }, { label: "诊断 / 结论", value: diagnosis }, { label: "识别页数", value: "浏览器内解析" }, { label: "指标字段", value: `${values.length} 项` }, { label: "文本长度", value: `${text.length} 字` }];
  const guidance = ["预约相关专科，携带原始 PDF 和既往检查结果。", "向医生确认每个异常描述的临床意义、是否需要复查及复查时间。", "如果出现持续胸痛、呼吸困难、意识改变等急症症状，请直接联系急救服务。"];
  return { file: file.name, summary, fields, values, findings, guidance, analyzedAt: new Date().toISOString() };
}
function render(result) {
  state.result = result; $("#result-empty").classList.add("hidden"); $("#result-content").classList.remove("hidden"); $("#result-title").textContent = result.file.replace(/\.pdf$/i, "") + " · 分析结果"; $("#summary").textContent = result.summary;
  $("#field-grid").innerHTML = result.fields.map(f => `<div class="field"><label>${f.label}</label><strong>${escapeHtml(f.value)}</strong></div>`).join("");
  $("#abnormal-count").textContent = `${result.findings.length} 项`;
  $("#abnormal-list").innerHTML = result.findings.length ? result.findings.map(f => `<div class="abnormal ${f.high ? "high" : ""}"><i data-lucide="${f.high ? "alert-triangle" : "circle-alert"}"></i><div><strong>${f.title}</strong><p>${escapeHtml(f.detail)}</p></div></div>`).join("") : `<div class="abnormal"><i data-lucide="circle-check"></i><div><strong>未发现明显异常关键词</strong><p>这不代表报告完全正常，请以医生的正式解读为准。</p></div></div>`;
  $("#guidance-list").innerHTML = result.guidance.map(item => `<li>${escapeHtml(item)}</li>`).join(""); setIcons();
}
async function enhanceWithAgents(result) {
  const payload = { projectId: state.activeProjectId, fileName: state.file.name, text: state.text, pdfBase64: await toBase64(state.file), config: state.config };
  const response = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  if (!response.ok) throw new Error((await response.json()).error || "服务端分析失败");
  const data = await response.json();
  if (data.text && data.text !== state.text) { state.text = data.text; result = analyze(state.text, state.file); }
  if (data.ai) { result.summary = data.ai.summary || result.summary; result.findings = Array.isArray(data.ai.findings) ? data.ai.findings : result.findings; result.guidance = Array.isArray(data.ai.guidance) ? data.ai.guidance : result.guidance; result.agentMeta = data.meta; }
  return result;
}
function toBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = reject; reader.readAsDataURL(file); }); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
function download(type) { if (!state.result) return; const r = state.result; let body, name, mime; if (type === "json") { body = JSON.stringify(r, null, 2); name = "medical-report-analysis.json"; mime = "application/json"; } else { body = `# ${r.file} · 医学报告分析\n\n## 一页摘要\n${r.summary}\n\n## 关键字段\n${r.fields.map(f => `- ${f.label}：${f.value}`).join("\n")}\n\n## 需要关注\n${r.findings.length ? r.findings.map(f => `- ${f.title}：${f.detail}`).join("\n") : "- 未发现明显异常关键词"}\n\n## 就医沟通准备\n${r.guidance.map(g => `- ${g}`).join("\n")}\n\n> 本结果仅用于信息整理，不构成医疗诊断。`; name = "medical-report-analysis.md"; mime = "text/markdown"; } const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([body], { type: mime })); a.download = name; a.click(); URL.revokeObjectURL(a.href); }

dropzone.addEventListener("click", () => input.click()); $("#choose-button").addEventListener("click", e => { e.stopPropagation(); input.click(); }); input.addEventListener("change", e => uploadFiles(e.target.files)); ["dragenter", "dragover"].forEach(type => dropzone.addEventListener(type, e => { e.preventDefault(); dropzone.classList.add("dragover"); })); ["dragleave", "drop"].forEach(type => dropzone.addEventListener(type, e => { e.preventDefault(); dropzone.classList.remove("dragover"); })); dropzone.addEventListener("drop", e => uploadFiles(e.dataTransfer.files)); $("#remove-file").addEventListener("click", resetFile);
async function pollProjectAnalysis(){for(let attempt=0;attempt<240;attempt++){const data=await api(`/api/projects/${state.activeProjectId}/analysis-summary`);await loadProjects();renderUploadedFiles();const done=data.files.filter(file=>file.kind==="pdfs"&&file.status==="已完成").length,total=data.files.filter(file=>file.kind==="pdfs").length;showStatus(`正在分析 ${done}/${total} 份报告…`);if(data.status!=="处理中"){progress.classList.remove("active");if(data.summary){render(data.summary);showStatus("全部报告已汇总，请审核异常项与来源")}else showStatus(data.error||"项目分析失败",true);renderUploadedFiles();return}await new Promise(resolve=>setTimeout(resolve,3000))}progress.classList.remove("active");showStatus("分析仍在后台进行，可稍后重新打开项目查看",true)}
analyzeButton.addEventListener("click",async()=>{if(!state.activeProjectId)return showStatus("请先打开一个项目",true);analyzeButton.disabled=true;progress.classList.add("active");showStatus("正在创建批量解析任务…");try{await api(`/api/projects/${state.activeProjectId}/analyze-all`,{method:"POST",body:"{}"});await pollProjectAnalysis()}catch(error){progress.classList.remove("active");showStatus(`无法启动分析：${error.message}`,true);await loadProjects();renderUploadedFiles()}});
$("#download-md").addEventListener("click", () => download("md")); $("#download-json").addEventListener("click", () => download("json")); setIcons();
const settingsModal = $("#settings-modal");
function openSettings() { const c = state.config; $("#deepseek-key").value = c.deepseek?.key || ""; $("#deepseek-url").value = c.deepseek?.url || "https://api.deepseek.com"; $("#mineru-key").value = c.mineru?.token || ""; $("#mineru-url").value = c.mineru?.url?.replace("/api/v1/file-urls/batch-upload","/api/v4") || "https://mineru.net/api/v4"; settingsModal.classList.add("open"); settingsModal.setAttribute("aria-hidden", "false"); }
function closeSettings() { settingsModal.classList.remove("open"); settingsModal.setAttribute("aria-hidden", "true"); }
function readConfig() { return { deepseek: { key: $("#deepseek-key").value.trim(), url: $("#deepseek-url").value.trim() || "https://api.deepseek.com" }, mineru: { token: $("#mineru-key").value.trim(), url: $("#mineru-url").value.trim() || "https://mineru.net/api/v4" } }; }
$("#settings-button").addEventListener("click", openSettings); $("#close-settings").addEventListener("click", closeSettings); $("#cancel-settings").addEventListener("click", closeSettings);
$("#save-settings").addEventListener("click", () => { state.config = readConfig(); localStorage.setItem("medsight-api-config", JSON.stringify(state.config)); closeSettings(); showStatus("API 配置已保存"); });
document.querySelectorAll(".test-api").forEach(button => button.addEventListener("click", async () => { const service = button.dataset.service; const cfg = readConfig()[service]; const output = $("#" + service + "-status"); output.textContent = "测试中…"; output.className = "connection-status pending"; button.disabled = true; try { const r = await fetch("/api/test-connection", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ service, config: cfg }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); output.textContent = data.message || "连接成功"; output.className = "connection-status success"; } catch (error) { output.textContent = error.message || "连接失败"; output.className = "connection-status error"; } finally { button.disabled = false; } }));
async function openCase(){if(!state.activeProjectId)return showStatus("请先打开一个项目",true);const d=await api(`/api/projects/${state.activeProjectId}/case`),c=d.caseData||{};const fields=[['patient','name','患者姓名'],['patient','gender','性别'],['patient','age','年龄'],['history','chiefComplaint','主诉'],['history','presentIllness','现病史'],['history','pastHistory','既往史'],['history','allergies','过敏史'],['history','medications','用药史'],['history','diagnosis','诊断']];$("#case-form").innerHTML=fields.map(([g,k,l])=>`<label class="case-field"><span>${l}</span><textarea data-group="${g}" data-key="${k}" placeholder="待补充">${escapeHtml(c[g]?.[k]||'')}</textarea></label>`).join('');renderIndicators(c.indicators||[]);$("#case-modal").classList.add("open");setIcons()}
function renderIndicators(items){const dims=['待分类','前置因素','诱发因素','介质因素','同化代谢','代谢转换与消除','结构完整性','防御与修护','传递系统','传输系统','能量生成','睡眠与放松','运动与活动','营养和水分','压力','人际社交关系'];const groups=new Map();(items||[]).forEach(x=>{const key=x.reportType||'其他报告';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)});let html='';for(const [type,group] of groups){html+=`<div class="indicator-group"><div class="indicator-group-title"><strong>${escapeHtml(type)}</strong><small>${group.length} 条候选指标</small></div>${group.map((x,i)=>{const tone=x.conflict?'conflict':x.duplicate?'duplicate':x.status==='异常'?'abnormal':'normal';return `<div class="field indicator-card ${tone}" data-file="${escapeHtml(x.source?.file||'')}" data-page="${x.source?.page||''}"><label class="indicator-name"><input type="checkbox" data-indicator-check="${i}"><span>${escapeHtml(x.name||'未命名指标')}</span></label><input data-indicator="${i}" value="${escapeHtml(x.name||'')}" aria-label="指标名称"><textarea data-indicator-value="${i}" aria-label="指标值">${escapeHtml(x.value||'')}</textarea><select data-indicator-dimension="${i}" aria-label="所属维度">${dims.map(d=>`<option ${d===(x.dimension||'待分类')?'selected':''}>${d}</option>`).join('')}</select><select data-indicator-review="${i}" aria-label="审核状态"><option ${x.reviewStatus==='待审核'?'selected':''}>待审核</option><option ${x.reviewStatus==='已确认'?'selected':''}>已确认</option><option ${x.reviewStatus==='已排除'?'selected':''}>已排除</option><option ${x.reviewStatus==='需补充'?'selected':''}>需补充</option></select><span class="indicator-badge">${x.conflict?'结果冲突':x.duplicate?'重复指标':x.status==='异常'?(x.severity||'异常'):'未见明显异常'}</span><small class="indicator-source">来源：${escapeHtml(x.source?.file||'未知文件')}<br>第 ${x.source?.page||'?'} 页</small></div>`}).join('')}</div>`}$("#indicator-list").innerHTML=html||'<p class="project-empty">暂无指标，请先提取</p>'}
async function openMatrix(){if(!state.activeProjectId)return showStatus("Open a project first",true);const d=await api(`/api/projects/${state.activeProjectId}/matrix`);$("#matrix-list").innerHTML=d.dimensions.map(x=>`<div class="field"><strong>${escapeHtml(x.name)}</strong><small>${x.items.length?`${x.items.length} linked indicators`:'No confirmed indicators'}</small>${x.items.slice(0,5).map(i=>`<p>${escapeHtml(i.name)}: ${escapeHtml(i.value)}</p>`).join('')}</div>`).join('');$("#matrix-modal").classList.add('open')}
function renderMatrixPage(d){const section=(title,body)=>`<section class="matrix-section"><h3>${title}</h3>${body}</section>`;const source=s=>s?.file?`<small class="matrix-source">来源：${escapeHtml(s.file)} · 第 ${s.page||'?'} 页</small>`:'';const dims=(d.dimensions||[]).map(x=>`<article class="matrix-dimension"><div class="matrix-dimension-head"><strong>${escapeHtml(x.name)}</strong><span class="matrix-status">${escapeHtml(x.assessmentStatus||'待人工确认')}</span></div><p>${escapeHtml(x.assessment||'')}</p>${(x.items||[]).map(i=>`<div class="matrix-indicator"><span>${escapeHtml(i.name)}：${escapeHtml(i.value||'')}</span>${source(i.source)}</div>`).join('')}${(x.sources||[]).map(source).join('')}</article>`).join('');const roots=(d.rootMechanisms||[]).map(x=>`<article class="matrix-insight"><strong>${escapeHtml(x.name)}</strong><p>${escapeHtml(x.detail)}</p>${(x.sources||[]).map(source).join('')}</article>`).join('')||'<p class="project-empty">暂无已确认异常可归纳。</p>';const factors=(d.threeFactors||[]).map(x=>`<article class="matrix-insight"><strong>${escapeHtml(x.name)}</strong><p>${escapeHtml(x.detail)}</p>${(x.sources||[]).map(source).join('')}</article>`).join('');const timeline=(d.timeline||[]).map(x=>`<div class="timeline-item"><strong>${escapeHtml(x.date||x.time||'待补充')}</strong><span>${escapeHtml(x.title||x.event||x.description||'')}</span>${(x.sources||[]).map(source).join('')}</div>`).join('')||'<p class="project-empty">暂无病例时间线，请在病例审核中补充。</p>';$("#matrix-page-content").innerHTML=section('维度综合评估',`<div class="matrix-dimensions">${dims}</div>`)+section('核心根源机制',`<div class="matrix-insights">${roots}</div>`)+section('三因素分析',`<div class="matrix-insights factors">${factors}</div>`)+section('健康事件时间线',`<div class="timeline">${timeline}</div>`)+`<p class="matrix-disclaimer">${escapeHtml(d.disclaimer||'所有结论需人工确认。')}</p>`;setIcons()}
async function openMatrixPage(){if(!state.activeProjectId)return showStatus('请先打开一个项目',true);try{const d=await api(`/api/projects/${state.activeProjectId}/matrix`);renderMatrixPage(d)}catch(e){showStatus(`矩阵加载失败：${e.message}`,true)}}
function setWorkflowStep(step){document.querySelectorAll('.workflow-tab').forEach(x=>x.classList.toggle('active',x.dataset.step===String(step)));document.querySelectorAll('.workflow-step').forEach(x=>x.classList.toggle('hidden',!x.classList.contains(`workflow-step-${step}`)));if(step===2)openMatrixPage();}
let suggestionState={generatedAt:null,suggestions:[],combinationAnalysis:[]};
function renderSuggestions(data){suggestionState={...data,suggestions:data.suggestions||[],combinationAnalysis:data.combinationAnalysis||[]};$("#suggestion-count").textContent=`${suggestionState.suggestions.length} 条建议 · ${suggestionState.suggestions.filter(x=>x.reviewStatus==='已确认').length} 条已确认`;$("#combination-analysis").innerHTML=suggestionState.combinationAnalysis.length?suggestionState.combinationAnalysis.map(x=>`<div class="combination-card"><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.detail)}</p><small>依据：${(x.indicators||[]).map(i=>escapeHtml(`${i.name} ${i.value||''}`)).join('、')}</small></div>`).join(''):'<div class="combination-card muted">暂无可生成的异常组合（需要至少两条已确认异常指标）。</div>';
  $("#suggestion-list").innerHTML=suggestionState.suggestions.length?suggestionState.suggestions.map((x,i)=>`<article class="suggestion-card ${x.category==='必须回避'?'avoid':x.category==='建议调整'?'adjust':'optional'}" data-suggestion-index="${i}"><div class="suggestion-card-head"><span class="suggestion-category">${escapeHtml(x.category)}</span><span class="suggestion-type">${escapeHtml(x.type)}</span><label class="suggestion-review"><input type="checkbox" data-suggestion-check ${x.reviewStatus==='已确认'?'checked':''}>确认</label></div><input class="suggestion-title-input" data-suggestion-title value="${escapeHtml(x.title||'')}"><textarea class="suggestion-content-input" data-suggestion-content>${escapeHtml(x.editableContent||x.content||'')}</textarea><div class="suggestion-evidence"><strong>触发依据</strong><span>${(x.basis||[]).map(b=>escapeHtml(`${b.name} ${b.value||''}`)).join('、')||'无已确认异常指标'}</span>${(x.sources||[]).map(s=>`<small>来源：${escapeHtml(s.file||'未知文件')} · 第 ${s.page||'?'} 页</small>`).join('')}</div></article>`).join(''):'<p class="project-empty">没有基于已确认异常指标生成建议。</p>';setIcons()}
async function openSuggestions(){if(!state.activeProjectId)return showStatus('请先打开一个项目',true);const d=await api(`/api/projects/${state.activeProjectId}/suggestions`);renderSuggestions(d);$("#suggestions-modal").classList.add('open')}
async function generateSuggestions(){if(!state.activeProjectId)return;const button=$("#generate-suggestions");button.disabled=true;try{const d=await api(`/api/projects/${state.activeProjectId}/suggestions`,{method:'POST',body:'{}'});renderSuggestions(d);showStatus(`已生成 ${d.suggestions?.length||0} 条建议草稿`)}catch(e){showStatus(`建议生成失败：${e.message}`,true)}finally{button.disabled=false}}
function collectSuggestions(){return Array.from(document.querySelectorAll('.suggestion-card')).map(card=>{const i=Number(card.dataset.suggestionIndex),old=suggestionState.suggestions[i]||{};const confirmed=card.querySelector('[data-suggestion-check]')?.checked;return {...old,title:card.querySelector('[data-suggestion-title]')?.value.trim()||old.title,editableContent:card.querySelector('[data-suggestion-content]')?.value.trim()||old.content,content:card.querySelector('[data-suggestion-content]')?.value.trim()||old.content,reviewStatus:confirmed?'已确认':'待审核'}})}
async function saveSuggestions(requireConfirmed=false){const suggestions=collectSuggestions();if(requireConfirmed&&suggestions.some(x=>x.reviewStatus!=='已确认'))return showStatus('仍有建议未确认，确认后才能用于 PPT',true);const d=await api(`/api/projects/${state.activeProjectId}/suggestions`,{method:'PUT',body:JSON.stringify({suggestions})});renderSuggestions(d);showStatus(requireConfirmed?'建议已确认，可进入 PPT':'建议审核结果已保存')}
$("#extract-indicators").addEventListener("click",async()=>{const d=await api(`/api/projects/${state.activeProjectId}/indicators`,{method:"POST"});renderIndicators(d.indicators);showStatus(`Extracted ${d.indicators.length} indicators`)})
async function saveCase(reviewed=false){const c={patient:{},history:{},indicators:[],sources:[]};document.querySelectorAll("#case-form textarea").forEach(x=>{if(x.dataset.group)c[x.dataset.group][x.dataset.key]=x.value.trim()});document.querySelectorAll("#indicator-list .field").forEach(row=>{const name=row.querySelector('[data-indicator]')?.value||"",value=row.querySelector('[data-indicator-value]')?.value||"";if(name)c.indicators.push({name,value,status:"待确认",reviewStatus:row.querySelector('[data-indicator-review]')?.value||"待审核",dimension:row.querySelector('[data-indicator-dimension]')?.value||"待分类",source:{file:row.dataset.file||"",page:row.dataset.page||null}})});await api(`/api/projects/${state.activeProjectId}/case`,{method:"PUT",body:JSON.stringify({caseData:c,reviewed})});await api(`/api/projects/${state.activeProjectId}/indicators`,{method:"PUT",body:JSON.stringify({indicators:c.indicators})});await loadProjects();renderProjects();$("#case-modal").classList.remove("open");showStatus(reviewed?"病例审核已确认":"病例草稿已保存")}
$("#close-case").addEventListener("click",()=>$("#case-modal").classList.remove("open"));$("#save-case").addEventListener("click",()=>saveCase(false));$("#confirm-case").addEventListener("click",()=>saveCase(true));$("#view-matrix").addEventListener("click",openMatrix);$("#bulk-confirm").addEventListener("click",()=>{document.querySelectorAll("[data-indicator-check]:checked").forEach(box=>{const review=box.closest(".indicator-card")?.querySelector("[data-indicator-review]");if(review)review.value="已确认"});showStatus("已批量确认勾选指标")});$("#close-matrix").addEventListener("click",()=>$("#matrix-modal").classList.remove("open"));$("#extract-indicators").addEventListener("click",async()=>{const d=await api(`/api/projects/${state.activeProjectId}/indicators`,{method:"POST"});renderIndicators(d.indicators);showStatus(`已提取 ${d.indicators.length} 个候选指标`)});$("#indicator-list").addEventListener("change",event=>{if(event.target.matches("[data-indicator-check]")){const card=event.target.closest(".indicator-card"),review=card?.querySelector("[data-indicator-review]");if(review&&event.target.checked)review.value="已确认"}});
document.addEventListener("dblclick",e=>{const row=e.target.closest(".project-item");if(row){const id=row.querySelector(".open-project")?.dataset.id;if(id){state.activeProjectId=id;openCase()}}});

$("#close-preview")?.addEventListener("click",()=>$("#preview-modal")?.classList.remove("open"));
document.querySelectorAll('.workflow-tab').forEach(tab=>tab.addEventListener('click',()=>setWorkflowStep(tab.dataset.step)));
$("#refresh-matrix-page")?.addEventListener('click',openMatrixPage);
$("#open-suggestions")?.addEventListener('click',()=>{ $("#matrix-modal").classList.remove('open'); openSuggestions(); });
$("#close-suggestions")?.addEventListener('click',()=>$("#suggestions-modal")?.classList.remove('open'));
$("#generate-suggestions")?.addEventListener('click',generateSuggestions);
$("#save-suggestions")?.addEventListener('click',()=>saveSuggestions(false));
$("#confirm-suggestions")?.addEventListener('click',()=>saveSuggestions(true));
$("#confirm-all-suggestions")?.addEventListener('click',()=>{document.querySelectorAll('[data-suggestion-check]').forEach(x=>x.checked=true);showStatus('已选中全部建议，请保存审核');});
