import http from "node:http";
import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import { extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createReadStream } from "node:fs";
import { createRequire } from "node:module";
const execFileAsync = promisify(execFile);
const require = createRequire(import.meta.url);
const PptxGenJS = require("pptxgenjs");

const root = fileURLToPath(new URL(".", import.meta.url));
const port = Number(process.env.PORT || 4173);
const mineruToken = process.env.MINERU_API_TOKEN || "";
const deepseekKey = process.env.DEEPSEEK_API_KEY || "";
const dataRoot = process.env.DATA_ROOT || join(root, "data", "projects");
const MAX_UPLOAD_BYTES = Number(process.env.MAX_UPLOAD_BYTES || 20 * 1024 * 1024);
const safe = (s) => String(s).replace(/[^\w\u4e00-\u9fff.-]+/g, "_").slice(0, 80);
async function projectDir(id){ const d=join(dataRoot,safe(id)); await mkdir(join(d,"source","screenshots"),{recursive:true}); await mkdir(join(d,"source","pdfs"),{recursive:true}); await mkdir(join(d,"parsed"),{recursive:true}); return d; }
function redactSecrets(value){const text=JSON.stringify(value??{});return JSON.parse(text.replace(/sk-[A-Za-z0-9_-]{12,}/g,"[REDACTED_API_KEY]"));}
async function logAction(id, action, detail={}){ const d=await projectDir(id), f=join(d,"audit-log.jsonl"); await writeFile(f, JSON.stringify({at:new Date().toISOString(),action,detail:redactSecrets(detail)})+"\n",{flag:"a"}); }
async function listProjects(){ await mkdir(dataRoot,{recursive:true}); const out=[]; for(const id of await readdir(dataRoot)){try{const d=await projectDir(id),p=JSON.parse(await readFile(join(d,"project.json")));out.push(p)}catch{}} return out.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)); }

async function jsonBody(req) {
  let raw = "";
  for await (const chunk of req) { raw += chunk; if (raw.length > 28 * 1024 * 1024) throw new Error("请求超过 28 MB"); if (raw.length > MAX_UPLOAD_BYTES * 1.4 + 1024 * 1024) throw new Error(`上传请求超过 ${Math.round(MAX_UPLOAD_BYTES / 1024 / 1024)} MB 文件限制`); }
  return JSON.parse(raw);
}
async function validatePdfFile(filePath){
  const {stdout}=await execFileAsync("pdfinfo",[filePath]);
  if(/Encrypted:\s+yes/i.test(stdout)) throw new Error("加密 PDF 暂不支持，请上传未加密文件");
  if(!/Pages:\s+\d+/i.test(stdout)) throw new Error("PDF 文件无法读取页数");
}

async function callMinerU(pdfBase64, fileName, config = {}) {
  const token = config.token || mineruToken; if (!token || !pdfBase64) return { text: "", skipped: true };
  const configuredBase = config.baseUrl || config.url || process.env.MINERU_API_BASE_URL || "https://mineru.net/api/v4";
  const base = configuredBase.replace(/\/file-urls\/(?:batch-upload|batch)\/?$/, "").replace(/\/api\/v1\/?$/, "/api/v4").replace(/\/$/, "");
  const headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
  const create = await fetch(`${base}/file-urls/batch`, { method: "POST", headers, body: JSON.stringify({ files: [{ name: fileName || "report.pdf", is_ocr: false }] }) });
  if (!create.ok) throw new Error(`MinerU task create ${create.status}`);
  const created = await create.json(); const data = created.data || created; const batchId = data.batch_id || data.batchId || data.id;
  const urls = data.file_urls || data.fileUrls || []; const uploadUrl = Array.isArray(urls) ? urls[0] : urls[fileName] || Object.values(urls)[0];
  if (!batchId || !uploadUrl) throw new Error("MinerU response missing batch_id or upload URL");
  const upload = await fetch(uploadUrl, { method: "PUT", body: Buffer.from(pdfBase64, "base64") }); if (!upload.ok) throw new Error(`MinerU file upload ${upload.status}`);
  let result = null; const timeout = Date.now() + Number(config.timeoutMs || process.env.MINERU_TIMEOUT_MS || 180000);
  while (Date.now() < timeout) { const poll = await fetch(`${base}/extract-results/batch/${encodeURIComponent(batchId)}`, { headers: { Authorization: `Bearer ${token}` } }); if (!poll.ok) throw new Error(`MinerU task status ${poll.status}`); const payload = await poll.json(); const rows = payload.data?.extract_result || payload.data?.results || payload.data || []; const row = Array.isArray(rows) ? (rows[0] || {}) : (rows[fileName] || Object.values(rows)[0] || {}); const state = String(row.state || row.status || payload.data?.status || "").toLowerCase(); if (["done","success","completed","succeeded"].includes(state) || row.full_zip_url || row.fullZipUrl || row.download_url) { result = { ...payload, row }; break; } if (["failed","error"].includes(state)) throw new Error(`MinerU task failed: ${row.err_msg || row.error || state}`); await new Promise(r => setTimeout(r, 3000)); }
  if (!result) throw new Error("MinerU task timeout");
  const zipUrl = result.row.full_zip_url || result.row.fullZipUrl || result.row.download_url || result.row.url; if (!zipUrl) return { text: result.row.markdown || result.row.text || "", pages: [], payload: result };
  const zipPath = join(dataRoot, `.mineru-${Date.now()}.zip`); const zip = await fetch(zipUrl); if (!zip.ok) throw new Error(`MinerU result download ${zip.status}`); await writeFile(zipPath, Buffer.from(await zip.arrayBuffer())); const outDir = `${zipPath}.dir`; await mkdir(outDir, { recursive: true }); await execFileAsync("unzip", ["-oq", zipPath, "-d", outDir]);
  const { stdout: files } = await execFileAsync("find", [outDir, "-type", "f"]); const pageFiles = files.split("\n").filter(x => /\.md$|\.json$/i.test(x)).sort(); const pages = []; for (const file of pageFiles) { const text = await readFile(file, "utf8"); pages.push({ file: file.replace(`${outDir}/`, ""), text, page: pages.length + 1 }); }
  await rm(zipPath, { force: true }); await rm(outDir, { recursive: true, force: true }); return { text: pages.map(x => `\n[Page ${x.page}]\n${x.text}`).join("\n"), pages, payload: result };
}

async function callDeepSeek(text, fileName, config = {}) {
  const key = config.key || deepseekKey; if (!key) return null;
  const base = (config.url || "https://api.deepseek.com").replace(/\/$/, "");
  const response = await fetch(`${base}/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
    body: JSON.stringify({ model: "deepseek-chat", temperature: 0.2, response_format: { type: "json_object" }, messages: [
      { role: "system", content: "你是医学报告信息整理助手。只能基于原文整理，不做诊断、不推荐药物。输出严格 JSON，字段为 summary(string), findings(array of {title,detail,high}), guidance(array of string), disclaimer(string)。用简体中文，清楚标注不确定性。" },
      { role: "user", content: `文件：${fileName}\n请分析以下医学报告文本：\n${text.slice(0, 50000)}` },
    ] }),
  });
  if (!response.ok) throw new Error(`DeepSeek 返回 ${response.status}`);
  const payload = await response.json();
  const content = payload?.choices?.[0]?.message?.content || "{}";
  return JSON.parse(content);
}
async function callVision(imageBase64, fileName, config = {}) { const key=config.key||deepseekKey;if(!key)return null;const base=(config.url||process.env.DEEPSEEK_API_URL||"https://api.deepseek.com").replace(/\/$/,"");const model=config.model||process.env.DEEPSEEK_VISION_MODEL||"deepseek-v4-flash-vision-exp";const r=await fetch(`${base}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:0,response_format:{type:"json_object"},messages:[{role:"system",content:"Extract only visible facts from this clinic screenshot. Return strict JSON with patient, history, symptoms, allergies, medications, visits, diagnosis, timeline. Missing or uncertain values must be null and reviewStatus must be 待人工确认. Never guess."},{role:"user",content:[{type:"text",text:`File: ${fileName}`},{type:"image_url",image_url:{url:`data:image/png;base64,${imageBase64}`}}]}]})});if(!r.ok)throw new Error(`Vision model ${r.status}`);const j=await r.json();return {model,raw:j,structured:JSON.parse(j.choices?.[0]?.message?.content||"{}")}; }
function parseReportType(name,text){const s=`${name} ${text}`;if(/肠道菌群|宏基因组/.test(s))return"gut-microbiome";if(/食物不耐受|food.?intolerance/i.test(s))return"food-intolerance";if(/营养与毒性元素|头发/.test(s))return"nutrient-toxic-elements";if(/肠道功能健康评估|GI Function/.test(s))return"gi-function";return"unknown"}
function extractStructuredIndicators(pages,fileName,type){const out=[];for(const pg of pages||[]){for(const line of String(pg.text||"").split(/\n|。/).map(x=>x.trim()).filter(Boolean)){const m=line.match(/([\u4e00-\u9fa5A-Za-z][\u4e00-\u9fa5A-Za-z0-9（）()\-]{1,30})\s*[:：]?\s*([<>≤≥]?\s*\d+(?:\.\d+)?)\s*([A-Za-zμ%/]+)?(?:\s*(?:参考值|参考范围)\s*[:：]?\s*([<>]?\s*\d+(?:\.\d+)?(?:\s*[-~至]\s*\d+(?:\.\d+)?|\s*[A-Za-zμ%/]+)?))?/);if(!m)continue;const abnormal=/(偏高|偏低|异常|升高|降低|超标|阳性|↑|↓|重度|中度|轻度)/.test(line);const level=/(显著异常|重度|中度|轻度)/.exec(line)?.[1]||null;out.push({name:m[1],value:m[2],unit:m[3]||null,reference:m[4]||null,status:abnormal?"异常":"正常",severity:level|| (abnormal?"异常":"正常"),reviewStatus:"待审核",reportType:type,raw:line.slice(0,300),source:{file:fileName,page:pg.page}});if(out.length>=500) return out;}}return out}
function extractKeyConclusions(pages,type,fileName){const lines=(pages||[]).flatMap(pg=>String(pg.text||'').split(/\n|。/).map(x=>({text:x.trim(),page:pg.page}))).filter(x=>x.text&&/(结论|结 果|提示|评估|印象|建议|阳性|异常|风险)/.test(x.text));return lines.slice(0,20).map(x=>({text:x.text.slice(0,500),source:{file:fileName,page:x.page},reportType:type}));}

function classifyIndicators(items){const noise=/^(采检日期|检测日期|报告日期|年龄|性别|姓名|电话|编号|页码|说明|备注|单位|参考|项目)$/;const filtered=items.filter(item=>item.name.length>1&&!noise.test(item.name)&&!/^20\d{2}$/.test(item.value));const groups=new Map();for(const item of filtered){const key=item.name.replace(/[（）()\s]/g,"").toLowerCase();const group=groups.get(key)||[];group.push(item);groups.set(key,group)}return filtered.map(item=>{const key=item.name.replace(/[（）()\s]/g,"").toLowerCase(),group=groups.get(key)||[],values=new Set(group.map(x=>`${x.value}|${x.unit||""}`));return {...item,duplicate:group.length>1,conflict:values.size>1,severity:item.status==="异常"?"异常":"未见明显异常"}})}
function suggestionBasis(indicator){return {name:indicator.name,value:indicator.value,unit:indicator.unit||null,reference:indicator.reference||null,source:indicator.source||{}}}
function buildSuggestions(project){
  const confirmed=(project.indicators||[]).filter(x=>x.reviewStatus==="已确认"); const abnormal=confirmed.filter(x=>x.status==="异常"||x.severity&&x.severity!=="未见明显异常");
  const text=abnormal.map(x=>`${x.name} ${x.value||""} ${x.raw||""}`).join(" "); const hasFood=/食物|不耐受|过敏|IgE|敏感/i.test(text),hasGut=/肠道|菌群|消化|吸收|便/i.test(text),hasToxic=/毒性|铅|汞|镉|砷|元素/i.test(text),hasNutrient=/维生素|矿物质|锌|硒|镁|铁|营养/i.test(text);
  const basis=abnormal.slice(0,8).map(suggestionBasis),sources=[...new Map(basis.map(x=>[`${x.source.file}|${x.source.page}`,x.source])).values()],suggestions=[];
  const add=(category,type,title,content,when=true)=>{if(when)suggestions.push({id:`suggestion-${Date.now()}-${suggestions.length}`,sourceType:"template",category,type,title,content,editableContent:content,basis,sources,reviewStatus:"待审核"})};
  add("必须回避","饮食","先暂停明确提示敏感/不耐受的食物","在人工复核敏感等级、症状关联和替代食物前，暂时回避报告中明确标记为显著异常的相关食物；不要自行扩大忌口范围。",hasFood);
  add("必须回避","营养支持","避免自行使用高剂量补充剂","在毒性元素或营养异常未完成专业复核前，不自行叠加同类补充剂或高剂量产品；本建议不包含剂量。",hasToxic||hasNutrient);
  add("建议调整","饮食","建立可追踪的饮食与症状记录","连续记录饮食、症状和排便变化，配合专业人员评估，优先选择未提示异常且耐受良好的食物。",hasFood||hasGut);
  add("建议调整","饮食","食物替代：优先选择耐受良好的同类食物","在确认敏感源后，使用营养结构相近且未提示异常的食物进行替代；具体清单需人工审核。",hasFood);
  add("可选建议","饮食","每餐饮食：保持蛋白质、蔬菜和主食的基本结构","根据个体耐受情况安排规律三餐，优先使用已确认可接受的食材，避免自行扩大限制范围。",hasFood||hasGut||abnormal.length>0);
  add("建议调整","运动","采用循序渐进的活动安排","从低至中等强度、可耐受的活动开始，根据症状和专业意见逐步调整；出现不适时停止并咨询医生。",abnormal.length>0);
  add("建议调整","饮水","保持规律饮水并记录变化","分散到全天饮水，结合活动量、天气和医生意见调整；如有饮水限制，以专业人员要求为准。",abnormal.length>0);
  add("建议调整","减压","加入每日可执行的放松安排","安排短时呼吸练习、规律作息或低负荷放松活动，并记录睡眠与压力变化，供后续复核。",hasGut||abnormal.length>1);
  add("可选建议","营养支持","优先从日常饮食补足多样性","在确认指标和饮食耐受范围后，优先通过多样化食物获得营养；是否需要补充剂由医生或营养师决定。",hasNutrient||hasGut||abnormal.length>0);
  add("可选建议","运动","记录活动后的主观感受","可选择散步、拉伸等低门槛活动，记录时长、强度和次日反应，作为人工调整依据。",abnormal.length>0);
  return {generatedAt:new Date().toISOString(),basedOnIndicatorCount:confirmed.length,confirmedAbnormalCount:abnormal.length,combinationAnalysis:abnormal.length>=2?[{title:"多个已确认异常需要联合评估",detail:`当前有 ${abnormal.length} 条已确认异常指标，建议结合症状、时间线和来源页码进行人工综合判断，不将单项结果视为诊断。`,indicators:abnormal.slice(0,12).map(suggestionBasis),sources}]:[],suggestions,disclaimer:"建议仅基于已确认指标生成草稿，不构成诊断、治疗或用药建议；必须人工审核后才可进入 PPT。"};
}
const runningProjects = new Set();
function indicatorSuggestion(indicator){const suggestions={"food-intolerance":"结合症状记录与医生或营养师复核，不要仅凭单项结果长期扩大忌口范围。","nutrient-toxic-elements":"结合参考范围、症状和其他检查复核；补充剂类型与剂量需由专业人员确认。","gut-microbiome":"结合消化道症状和临床评估复核，不依据单项菌群结果自行治疗。","gi-function":"建议结合消化症状、饮食记录和医生评估，必要时由医生确定复查项目。"};return suggestions[indicator.reportType]||"请结合症状、既往史和医生意见复核，不根据单一指标自行诊断或用药。"}
async function analyzeStoredPdf(projectId,file){const d=await projectDir(projectId),pdf=await readFile(join(d,"source",file.kind,file.name));let mineruError="",mineru={text:"",pages:[]};try{mineru=await callMinerU(pdf.toString("base64"),file.name,{})}catch(error){mineruError=error.message}const sourceText=mineru.text||"",reportType=parseReportType(file.originalName||file.name,sourceText),structuredIndicators=extractStructuredIndicators(mineru.pages||[],file.originalName||file.name,reportType);await writeFile(join(d,"parsed",`${safe(file.name)}.json`),JSON.stringify({fileName:file.originalName||file.name,reportType,text:sourceText,pages:mineru.pages||[],structuredIndicators,meta:{mineru:!mineruError,mineruError}},null,2));const p=JSON.parse(await readFile(join(d,"project.json")));p.files=(p.files||[]).map(item=>item.name===file.name?{...item,status:mineruError?"失败":"已完成",queueStatus:mineruError?"failed":"completed",parsedAt:new Date().toISOString(),error:mineruError||undefined}:item);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(projectId,"analysis.file.completed",{fileName:file.name,ok:!mineruError,indicatorCount:structuredIndicators.length})}
async function buildProjectSummary(projectId){const d=await projectDir(projectId),p=JSON.parse(await readFile(join(d,"project.json"))),indicators=[];for(const file of p.files||[]){if(file.kind!=="pdfs")continue;try{const parsed=JSON.parse(await readFile(join(d,"parsed",`${safe(file.name)}.json`)));indicators.push(...(parsed.structuredIndicators||[]))}catch{}}const unique=[...new Map(indicators.map(item=>[`${item.name}|${item.value}|${item.source?.file}|${item.source?.page}`,item])).values()],abnormal=unique.filter(item=>item.status==="异常");const findings=abnormal.slice(0,30).map(item=>({title:`${item.name} ${item.value}${item.unit?` ${item.unit}`:""}`,detail:`${item.raw||"报告标记异常"}；来源：${item.source?.file||"未知文件"}，第 ${item.source?.page||"?"} 页。${indicatorSuggestion(item)}`,high:true}));const completed=(p.files||[]).filter(file=>file.kind==="pdfs"&&file.status==="已完成").length,total=(p.files||[]).filter(file=>file.kind==="pdfs").length;return {file:`${p.name}·项目综合分析`,summary:`已汇总 ${completed}/${total} 份 PDF，提取 ${unique.length} 条候选指标，其中 ${abnormal.length} 条被报告原文标记为异常。所有结果仍需人工核对原文和页码后才能进入矩阵与 PPT。`,fields:[{label:"报告数量",value:`${completed}/${total} 份已完成`},{label:"候选指标",value:`${unique.length} 项`},{label:"异常候选",value:`${abnormal.length} 项`},{label:"审核状态",value:"待人工审核"}],values:unique.slice(0,20),findings,guidance:["先核对每条异常项的指标值、单位、参考范围、文件名和页码。","将异常项与症状、既往史及其他检查结果联合评估，避免孤立解读。","饮食、运动、饮水、减压和营养支持建议需经人工审核；暂不自动生成药物或补充剂剂量。"],analyzedAt:new Date().toISOString()}}
async function analyzeProject(projectId){runningProjects.add(projectId);try{const d=await projectDir(projectId),p=JSON.parse(await readFile(join(d,"project.json"))),pending=(p.files||[]).filter(file=>file.kind==="pdfs"&&file.status!=="已完成");p.status="处理中";p.files=(p.files||[]).map(file=>pending.some(item=>item.name===file.name)?{...file,status:"处理中",queueStatus:"queued"}:file);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));for(const file of pending)await analyzeStoredPdf(projectId,file);const summary=await buildProjectSummary(projectId),latest=JSON.parse(await readFile(join(d,"project.json")));latest.analysisSummary=summary;latest.status=(latest.files||[]).some(file=>file.kind==="pdfs"&&file.status==="失败")?"失败":"待审核";latest.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(latest,null,2));await writeFile(join(d,"parsed","project-summary.json"),JSON.stringify(summary,null,2));await logAction(projectId,"analysis.project.completed",{pdfCount:(latest.files||[]).filter(file=>file.kind==="pdfs").length,abnormalCount:summary.findings.length})}finally{runningProjects.delete(projectId)}}

function send(res, status, body) { res.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Access-Control-Allow-Origin": "*" }); res.end(JSON.stringify(body)); }
async function generateProjectPpt(projectId){
  const d=await projectDir(projectId),p=JSON.parse(await readFile(join(d,"project.json"))),confirmed=(p.indicators||[]).filter(x=>x.reviewStatus==="已确认"),sugs=(p.suggestions?.suggestions||[]).filter(x=>x.reviewStatus==="已确认"),interventionPeriod=p.suggestions?.interventionPeriod||"未填写",reviewPeriod=p.suggestions?.reviewPeriod||"未填写";
  if(!confirmed.length) throw new Error("没有已确认指标，无法导出 PPT"); if((p.indicators||[]).some(x=>!['已确认','已排除'].includes(x.reviewStatus))) throw new Error("仍有指标未完成审核，无法导出 PPT"); if((p.suggestions?.suggestions||[]).some(x=>!['已确认','已排除'].includes(x.reviewStatus))) throw new Error("仍有建议未完成审核，无法导出 PPT"); if(!sugs.length) throw new Error("没有已确认建议，无法导出 PPT");
  const pptx=new PptxGenJS(); pptx.layout="LAYOUT_WIDE"; pptx.author="医见 MEDSIGHT"; pptx.subject="健康改善指导方案"; pptx.title="健康改善指导方案"; pptx.lang="zh-CN";
  const C={ink:"17231F",green:"39765A",mint:"E8F4EB",paper:"F6F8F5",muted:"64746B",red:"B84E47",amber:"B97924"}; const name=p.caseData?.patient?.name||p.patientName||"患者";
  const title=(s,k,t,sub="")=>{s.background={color:C.paper};s.addText(k,{x:.6,y:.45,w:3,h:.2,fontFace:"Arial",fontSize:10,color:C.green,bold:true,margin:0});s.addText(t,{x:.6,y:.8,w:12,h:.5,fontFace:"Arial",fontSize:26,bold:true,color:C.ink,margin:0});if(sub)s.addText(sub,{x:.6,y:1.4,w:11.8,h:.3,fontFace:"Arial",fontSize:12,color:C.muted,margin:0});}; const footer=s=>s.addText("医见 MEDSIGHT · 仅供信息整理，需由专业人员审核",{x:.6,y:7.1,w:12,h:.18,fontFace:"Arial",fontSize:8,color:"8B9690",margin:0,align:"right"});
  let s=pptx.addSlide();s.background={color:C.ink};s.addText("医见 MEDSIGHT",{x:.7,y:.7,w:4,h:.3,fontFace:"Arial",fontSize:13,color:"B9E6C5",bold:true,margin:0});s.addText("健康改善指导方案",{x:.7,y:2.2,w:11.5,h:.8,fontFace:"Arial",fontSize:34,color:"FFFFFF",bold:true,margin:0});s.addText(`${name} · 个性化报告`,{x:.7,y:3.2,w:8,h:.35,fontFace:"Arial",fontSize:16,color:"D6EBDD",margin:0});footer(s);
  s=pptx.addSlide();title(s,"01 / OVERVIEW","整体情况概览",`基于 ${confirmed.length} 条已确认指标与 ${sugs.length} 条已确认建议`);s.addText(`当前共纳入 ${confirmed.length} 条人工确认指标，其中 ${confirmed.filter(x=>x.status==='异常').length} 条被报告标记为异常。以下内容仅作为沟通准备，不能替代医生诊断。`,{x:.9,y:2.4,w:11,h:.8,fontFace:"Arial",fontSize:18,color:C.ink,margin:0,fit:"shrink"});footer(s);
  const dims=[...new Set(confirmed.map(x=>x.dimension||"待分类"))];s=pptx.addSlide();title(s,"02 / MATRIX","功能医学矩阵","已确认指标按功能维度归类");dims.slice(0,8).forEach((dim,i)=>{const x=.7+(i%2)*6.1,y=2+(Math.floor(i/2))*1.1,items=confirmed.filter(v=>(v.dimension||"待分类")===dim);s.addText(`${dim}  ·  ${items.length} 条已确认 / ${items.filter(v=>v.status==='异常').length} 条异常`,{x,y,w:5.6,h:.35,fontFace:"Arial",fontSize:15,color:C.ink,margin:0});});footer(s);
  const abnormal=confirmed.filter(x=>x.status==='异常');s=pptx.addSlide();title(s,"03 / PRIORITY FINDINGS","重点关注项","来源信息保留在报告数据中");s.addText(abnormal.slice(0,10).map(x=>`${x.name}：${x.value||''}（${x.source?.file||'未知文件'} · 第 ${x.source?.page||'?'} 页）`).join("\n")||"未见已确认异常项",{x:.9,y:2,w:11,h:3,fontFace:"Arial",fontSize:16,color:C.ink,breakLine:false,margin:0,fit:"shrink"});footer(s);
  for(const type of ["饮食","运动","饮水","减压","营养支持"]){const list=sugs.filter(x=>x.type===type),lines=list.length?list.map(x=>`${x.category}：${x.title}：${x.editableContent||x.content||''}`):["未生成已确认建议"];for(let page=0;page<lines.length;page+=5){const text=lines.slice(page,page+5).join("\n");s=pptx.addSlide();title(s,`04 / ${type}`,`${type}建议${lines.length>5?`（${Math.floor(page/5)+1}）`:''}`,`仅展示已确认建议`);s.addText(text,{x:.9,y:2,w:11,h:3.6,fontFace:"Arial",fontSize:15,color:C.ink,breakLine:false,margin:0,fit:"shrink"});footer(s);}}
  for(const [key,label] of [["回避","饮食回避"],["替代","食物替代"],["每餐","每餐饮食"]]){const list=sugs.filter(x=>x.type==="饮食"&&new RegExp(key).test(x.title));if(!list.length)continue;s=pptx.addSlide();title(s,`05 / ${label}`,label,"仅展示已确认建议");s.addText(list.map(x=>`${x.category}：${x.editableContent||x.content||''}`).join("\n"),{x:.9,y:2,w:11,h:3.6,fontFace:"Arial",fontSize:15,color:C.ink,breakLine:false,margin:0,fit:"shrink"});footer(s);}
  s=pptx.addSlide();title(s,"09 / PLAN","干预方案","周期由人工填写");s.addText(`干预周期：${interventionPeriod}\n复查周期：${reviewPeriod}\n\n执行前请结合个体情况与专业人员意见确认。`,{x:.9,y:2,w:11,h:2.4,fontFace:"Arial",fontSize:17,color:C.ink,breakLine:false,margin:0,fit:"shrink"});footer(s);
  s=pptx.addSlide();title(s,"08 / NEXT STEPS","后续沟通重点");s.addText("• 核对异常指标的原始报告、单位、参考范围与页码\n• 结合症状、既往史和时间线判断关联性\n• 生活方式建议执行前确认个体限制和适用范围\n• 本方案不包含药物或补充剂剂量",{x:.9,y:2,w:11,h:2.4,fontFace:"Arial",fontSize:17,color:C.ink,breakLine:false,margin:0,fit:"shrink"});footer(s);
  const outName=`${safe(name)}-健康改善指导方案-${Date.now()}.pptx`,outPath=join(d,"exports",outName);await mkdir(join(d,"exports"),{recursive:true});await pptx.writeFile({fileName:outPath});p.exports=[...(p.exports||[]),{name:outName,createdAt:new Date().toISOString(),kind:"pptx",slideCount:pptx._slides?.length||0}];p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(projectId,"ppt.exported",{name:outName});return {name:outName,slideCount:pptx._slides?.length||0};
}
async function buildExportData(projectId){
  const d=await projectDir(projectId),p=JSON.parse(await readFile(join(d,"project.json")));
  const indicators=(p.indicators||[]).filter(x=>x.reviewStatus==="已确认");
  const suggestions=(p.suggestions?.suggestions||[]).filter(x=>x.reviewStatus==="已确认");
  const files=(p.files||[]).map(x=>({name:x.name,originalName:x.originalName,kind:x.kind,size:x.size,status:x.status,uploadedAt:x.uploadedAt,sourceDirectory:`source/${x.kind}`}));
  return {exportedAt:new Date().toISOString(),project:{id:p.id,name:p.name,patientName:p.patientName,status:p.status},caseData:p.caseData||{},indicators,suggestions,files,sourceDirectory:{pdfs:files.filter(x=>x.kind==="pdfs"),screenshots:files.filter(x=>x.kind==="screenshots")},disclaimer:"导出内容仅包含人工确认数据，不构成医疗诊断。"};
}
async function handler(req, res) {
  if (req.method === "OPTIONS") return send(res, 204, {});
  if (req.method === "GET" && req.url === "/api/health") return send(res,200,{ok:true,service:"medical-report-agent",uptime:process.uptime(),mineruConfigured:Boolean(mineruToken),deepseekConfigured:Boolean(deepseekKey),maxUploadBytes:MAX_UPLOAD_BYTES});
  const kc=req.url.match(/^\/api\/projects\/([^/]+)\/key-conclusions$/); if(kc&&req.method==="GET"){const d=await projectDir(kc[1]),p=JSON.parse(await readFile(join(d,"project.json"))),out=[];for(const f of p.files||[]){if(f.kind!=="pdfs")continue;try{const path=join(d,"parsed",`${safe(f.name)}.json`),x=JSON.parse(await readFile(path));const items=x.keyConclusions||extractKeyConclusions(x.pages||[],x.reportType||"unknown",x.fileName||f.originalName||f.name);if(!x.keyConclusions){x.keyConclusions=items;await writeFile(path,JSON.stringify(x,null,2));}out.push(...items);}catch{}}return send(res,200,{keyConclusions:out});}
  const ej=req.url.match(/^\/api\/projects\/([^/]+)\/export-json$/); if(ej&&req.method==="GET"){return send(res,200,await buildExportData(ej[1]));}
  const sd=req.url.match(/^\/api\/projects\/([^/]+)\/source-directory$/); if(sd&&req.method==="GET"){const data=await buildExportData(sd[1]);return send(res,200,{project:data.project,sourceDirectory:data.sourceDirectory,generatedAt:data.exportedAt});}
  const eh=req.url.match(/^\/api\/projects\/([^/]+)\/exports$/); if(eh&&req.method==="GET"){const d=await projectDir(eh[1]),p=JSON.parse(await readFile(join(d,"project.json")));return send(res,200,{exports:p.exports||[]});}
  if (req.method === "GET" && req.url === "/api/projects") return send(res,200,{projects:await listProjects()});
  if (req.method === "POST" && req.url === "/api/projects") { const b=await jsonBody(req), now=new Date().toISOString(), id=`project-${Date.now()}`, p={id,name:String(b.name||"未命名项目"),patientName:"",status:"未开始",createdAt:now,updatedAt:now,files:[]}; const d=await projectDir(id); await writeFile(join(d,"project.json"),JSON.stringify(p,null,2)); await logAction(id,"project.create",{name:p.name}); return send(res,201,p); }
  const pm=req.url.match(/^\/api\/projects\/([^/]+)$/); if(pm && req.method==="DELETE"){const id=pm[1]; await rm(join(dataRoot,safe(id)),{recursive:true,force:true}); return send(res,200,{ok:true});}
  const pu=req.url.match(/^\/api\/projects\/([^/]+)\/upload$/); if(pu && req.method==="POST"){const id=pu[1],b=await jsonBody(req),d=await projectDir(id),original=String(b.name||"file"),kind=String(b.kind||"").toLowerCase(),dir=kind==="pdf"||original.toLowerCase().endsWith(".pdf")?"pdfs":"screenshots";let name=safe(original),n=1;while(true){try{await readFile(join(d,"source",dir,name));name=`${name.replace(/(\.[^.]+)?$/,"")}-${n++}${name.match(/\.[^.]+$/)?.[0]||""}`}catch{break}} await writeFile(join(d,"source",dir,name),Buffer.from(String(b.base64||""),"base64")); const p=JSON.parse(await readFile(join(d,"project.json"))); p.files=[...(p.files||[]),{name,originalName:original,kind:dir,status:"待解析",queueStatus:"queued",size:Number(b.size||0),uploadedAt:new Date().toISOString()}];p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(id,"file.upload",{name,kind:dir});return send(res,201,{ok:true,file:p.files.at(-1)});}
  const fd=req.url.match(/^\/api\/projects\/([^/]+)\/files\/([^/]+)$/); if(fd && req.method==="DELETE"){const id=fd[1],name=decodeURIComponent(fd[2]),d=await projectDir(id),p=JSON.parse(await readFile(join(d,"project.json")));const f=(p.files||[]).find(x=>x.name===name);if(f)await rm(join(d,"source",f.kind,name),{force:true});p.files=(p.files||[]).filter(x=>x.name!==name);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(id,"file.delete",{name});return send(res,200,{ok:true});}
  const raw=req.url.match(/^\/api\/projects\/([^/]+)\/files\/([^/]+)\/raw$/); if(raw && req.method==="GET"){const d=await projectDir(raw[1]),p=JSON.parse(await readFile(join(d,"project.json"))),requested=decodeURIComponent(raw[2]),f=(p.files||[]).find(x=>x.name===requested||x.originalName===requested);if(!f)return send(res,404,{error:"File not found"});const filePath=join(d,"source",f.kind,f.name);res.writeHead(200,{"Content-Type":f.kind==="pdfs"?"application/pdf":"application/octet-stream","Content-Disposition":`inline; filename*=UTF-8''${encodeURIComponent(f.name)}`,"Content-Length":String(f.size||0)});const stream=createReadStream(filePath);stream.on("error",error=>{if(!res.headersSent)return send(res,404,{error:error.message});res.destroy(error)});stream.pipe(res);return}
  const fr=req.url.match(/^\/api\/projects\/([^/]+)\/files\/([^/]+)$/); if(fr && req.method==="GET"){const id=fr[1],name=decodeURIComponent(fr[2]),d=await projectDir(id),p=JSON.parse(await readFile(join(d,"project.json"))),f=(p.files||[]).find(x=>x.name===name||x.originalName===name);if(!f)return send(res,404,{error:"File not found"});let parsed=null;try{parsed=JSON.parse(await readFile(join(d,"parsed",`${safe(name)}.json`)))}catch{}return send(res,200,{file:f,parsed,reviewed:p.reviewed||{},indicators:p.indicators||[]});}
  const cr=req.url.match(/^\/api\/projects\/([^/]+)\/case$/); if(cr && req.method==="GET"){const d=await projectDir(cr[1]),p=JSON.parse(await readFile(join(d,"project.json")));return send(res,200,{caseData:p.caseData||{patient:{},history:{},indicators:[],sources:[]},reviewed:p.reviewed||false});}
  if(cr && req.method==="PUT"){const d=await projectDir(cr[1]),b=await jsonBody(req),p=JSON.parse(await readFile(join(d,"project.json")));p.caseData=b.caseData||{};p.reviewed=Boolean(b.reviewed);p.status=p.reviewed?"已确认":"待审核";p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(cr[1],p.reviewed?"case.reviewed":"case.updated",{reviewed:p.reviewed});return send(res,200,{ok:true,caseData:p.caseData,reviewed:p.reviewed});}
  const ir=req.url.match(/^\/api\/projects\/([^/]+)\/indicators$/); if(ir && req.method==="POST"){const d=await projectDir(ir[1]),p=JSON.parse(await readFile(join(d,"project.json"))),items=[];const dims=[['肠道|菌群|消化|吸收','同化代谢'],['免疫|炎症|IgE|过敏','防御与修护'],['毒性|元素|铅|汞|钛|锡','代谢转换与消除'],['锌|硒|镁|钾|营养','营养和水分'],['能量|线粒体|代谢','能量生成'],['皮肤|屏障|甲|骨','结构完整性'],['神经|乙酰胆碱|多巴胺|睡眠','传递系统']];for(const f of p.files||[]){try{const x=JSON.parse(await readFile(join(d,"parsed",`${safe(f.name)}.json`)));const pages=x.pages||[{page:null,text:x.text||''}];for(const pg of pages){const lines=String(pg.text||'').split(/\n|。/).map(s=>s.trim()).filter(Boolean);for(const line of lines){const m=line.match(/([\u4e00-\u9fa5A-Za-z][\u4e00-\u9fa5A-Za-z0-9（）()\-]{1,30})\s*[:：]?\s*([<>≤≥]?\s*\d+(?:\.\d+)?(?:\s*[A-Za-zμ%/]+)?)/);if(!m)continue;const status=/(偏高|升高|超标|阳性|异常|↑|重度|中度)/.test(line)?'异常':'待确认';const dim=dims.find(([re])=>new RegExp(re,'i').test(line))?.[1]||'待分类';items.push({name:m[1],value:m[2],raw:line.slice(0,240),status,reviewStatus:'待审核',dimension:dim,source:{file:f.originalName||f.name,page:pg.page,locator:`page-${pg.page||'?'}`}});if(items.length>=300)break}if(items.length>=300)break} }catch{}}p.indicators=items;p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(ir[1],"indicators.extracted",{count:items.length,paged:true});return send(res,200,{indicators:items});}
  if(ir && req.method==="PUT"){const d=await projectDir(ir[1]),b=await jsonBody(req),p=JSON.parse(await readFile(join(d,"project.json")));p.indicators=Array.isArray(b.indicators)?b.indicators:[];p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(ir[1],"indicators.reviewed",{count:p.indicators.length});return send(res,200,{ok:true,indicators:p.indicators});}
  const mr=req.url.match(/^\/api\/projects\/([^/]+)\/matrix$/); if(mr && req.method==="GET"){const d=await projectDir(mr[1]),p=JSON.parse(await readFile(join(d,"project.json"))),confirmed=(p.indicators||[]).filter(x=>x.reviewStatus==="已确认"),dims=["前置因素","诱发因素","介质因素","同化代谢","代谢转换与消除","结构完整性","防御与修护","传递系统","传输系统","能量生成","睡眠与放松","运动与活动","营养和水分","压力","人际社交关系"],itemsFor=name=>confirmed.filter(x=>x.dimension===name),sourcesFor=items=>[...new Map(items.map(x=>[`${x.source?.file}|${x.source?.page}`,x.source||{}])).values()];const dimensions=dims.map(name=>{const items=itemsFor(name);return {name,items,assessment:items.length?`基于 ${items.length} 条已确认指标进行综合评估`:`当前未发现已确认指标`,assessmentStatus:items.length?"待人工确认":"未见明显异常",sources:sourcesFor(items)}});const abnormal=confirmed.filter(x=>x.status==="异常"),abnormalSources=sourcesFor(abnormal);const rootMechanisms=[];if(abnormal.some(x=>/肠道|菌群|消化|吸收|便/.test(`${x.name}${x.raw||""}`)))rootMechanisms.push({name:"肠道与同化代谢负担",detail:"已确认指标提示需要结合消化、吸收和排便相关信息综合评估。",indicators:abnormal.filter(x=>/肠道|菌群|消化|吸收|便/.test(`${x.name}${x.raw||""}`)),sources:sourcesFor(abnormal.filter(x=>/肠道|菌群|消化|吸收|便/.test(`${x.name}${x.raw||""}`))) });if(abnormal.some(x=>/食物|不耐受|过敏|IgE|敏感/.test(`${x.name}${x.raw||""}`)))rootMechanisms.push({name:"免疫敏感与暴露因素",detail:"已确认指标提示需要核对敏感源、暴露时间和症状关联。",indicators:abnormal.filter(x=>/食物|不耐受|过敏|IgE|敏感/.test(`${x.name}${x.raw||""}`)),sources:sourcesFor(abnormal.filter(x=>/食物|不耐受|过敏|IgE|敏感/.test(`${x.name}${x.raw||""}`))) });const threeFactors=[{name:"前置因素",detail:"病例背景、既往史、长期饮食和生活方式；需要人工补充与确认。",sources:[]},{name:"诱发因素",detail:"近期饮食、感染、压力、环境或暴露变化；需要结合时间线确认。",sources:abnormalSources},{name:"介质因素",detail:"已确认检测异常及其可能关联的功能维度；不作临床诊断。",sources:abnormalSources}];const timeline=(p.caseData?.history?.timeline||p.caseData?.timeline||[]).map(x=>({...x,sources:x.sources||[]}));return send(res,200,{confirmedIndicatorCount:confirmed.length,dimensions,rootMechanisms,threeFactors,timeline,disclaimer:"矩阵仅用于整理已确认信息，所有综合评估和根源机制均需专业人员人工确认。"});}
  const sy=req.url.match(/^\/api\/projects\/([^/]+)\/synthesis$/); if(sy && req.method==="GET"){const d=await projectDir(sy[1]),p=JSON.parse(await readFile(join(d,"project.json"))),confirmed=(p.indicators||[]).filter(x=>x.reviewStatus==="已确认"),abnormal=confirmed.filter(x=>x.status==="异常"),suggestions=(p.suggestions?.suggestions||[]).filter(x=>x.reviewStatus==="已确认"),groups=new Map();for(const x of confirmed){const key=x.dimension||"待分类";groups.set(key,(groups.get(key)||[]).concat(x));}const dimensions=[...groups].map(([name,items])=>({name,count:items.length,abnormalCount:items.filter(x=>x.status==="异常").length,assessment:items.some(x=>x.status==="异常")?`该维度有 ${items.filter(x=>x.status==="异常").length} 条已确认异常指标，需结合病例背景和原始报告进一步确认。`:`该维度已有 ${items.length} 条已确认指标，暂未见报告标记异常。`,indicators:items.slice(0,8),sources:[...new Map(items.map(x=>[`${x.source?.file}|${x.source?.page}`,x.source||{}])).values()]}));const sourceMap=[...new Map(abnormal.map(x=>[`${x.source?.file}|${x.source?.page}`,x.source||{}])).values()];const summary=confirmed.length?`当前共纳入 ${confirmed.length} 条人工确认指标，其中 ${abnormal.length} 条被报告标记为异常。综合分析应优先关注异常组合、对应功能维度和病例症状时间线。`:`当前暂无已确认指标，无法生成综合分析。`;return send(res,200,{generatedAt:new Date().toISOString(),confirmedIndicatorCount:confirmed.length,abnormalCount:abnormal.length,confirmedSuggestionCount:suggestions.length,summary,dimensions,priorityFindings:abnormal.slice(0,12).map(x=>({title:`${x.name} ${x.value||""}`,detail:x.raw||"已确认异常指标",source:x.source||{}})),combinationAnalysis:(p.suggestions?.combinationAnalysis||[]),confirmedSuggestions:suggestions,sources:sourceMap,reviewStatus:confirmed.length&&suggestions.length?"待人工确认":"资料不足",disclaimer:"综合分析仅基于已确认指标和已确认建议，不构成诊断；进入 PPT 前仍需人工确认。"});}
  const ex=req.url.match(/^\/api\/projects\/([^/]+)\/export-ppt$/); if(ex&&ex[1]&&req.method==="POST"){try{return send(res,200,{ok:true,...await generateProjectPpt(ex[1])})}catch(e){return send(res,400,{error:e.message})}}
  const rawExport=req.url.match(/^\/api\/projects\/([^/]+)\/exports\/([^/]+)$/); if(rawExport&&req.method==="GET"){const d=await projectDir(rawExport[1]),name=decodeURIComponent(rawExport[2]),filePath=join(d,"exports",safe(name));try{const stat=await import('node:fs/promises').then(m=>m.stat(filePath));res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.presentationml.presentation","Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(name)}`,"Content-Length":String(stat.size)});createReadStream(filePath).pipe(res);return}catch{return send(res,404,{error:"Export not found"})}}
  const pt=req.url.match(/^\/api\/projects\/([^/]+)\/ppt-template$/); if(pt&&req.method==="GET"){const d=await projectDir(pt[1]),p=JSON.parse(await readFile(join(d,"project.json"))),confirmed=(p.indicators||[]).filter(x=>x.reviewStatus==="已确认"),sugs=(p.suggestions?.suggestions||[]).filter(x=>x.reviewStatus==="已确认"),name=p.caseData?.patient?.name||p.patientName||"患者";const slides=[{key:"cover",title:"健康改善指导方案",subtitle:`${name} · 个性化报告`,status:"可编辑"},{key:"overview",title:"整体情况概览",content:`基于 ${confirmed.length} 条已确认指标整理`,status:"可编辑"},{key:"matrix",title:"功能医学矩阵",content:"展示已确认维度与重点指标",status:"可编辑"},{key:"findings",title:"重点关注项",content:`${confirmed.filter(x=>x.status==='异常').length} 条异常指标`,status:"可编辑"},{key:"diet",title:"饮食建议",content:sugs.filter(x=>x.type==='饮食').map(x=>x.editableContent||x.content).join("\n")||"待补充",status:"可编辑"},{key:"lifestyle",title:"运动、饮水与减压",content:sugs.filter(x=>['运动','饮水','减压'].includes(x.type)).map(x=>x.editableContent||x.content).join("\n")||"待补充",status:"可编辑"},{key:"nutrition",title:"营养支持",content:sugs.filter(x=>x.type==='营养支持').map(x=>x.editableContent||x.content).join("\n")||"待补充" ,status:"可编辑"},{key:"closing",title:"后续沟通重点",content:"请携带原始报告，与专业人员确认后续方案。",status:"可编辑"}];return send(res,200,{templateName:"敏医康健康改善指导方案",slideCount:slides.length,slides,ready:confirmed.length>0&&sugs.length>0,requirements:{confirmedIndicators:confirmed.length,confirmedSuggestions:sugs.length},disclaimer:"本阶段为 PPT 模板预览，实际文件导出在第 5 步完成。"});}
  const sg=req.url.match(/^\/api\/projects\/([^/]+)\/suggestions$/); if(sg && req.method==="POST"){const d=await projectDir(sg[1]),p=JSON.parse(await readFile(join(d,"project.json"))),data=buildSuggestions(p);p.suggestions=data;p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(sg[1],"suggestions.generated",{basedOnIndicatorCount:data.basedOnIndicatorCount,count:data.suggestions.length});return send(res,200,data);}
  if(sg && req.method==="GET"){const d=await projectDir(sg[1]),p=JSON.parse(await readFile(join(d,"project.json"))),data=p.suggestions||{generatedAt:null,basedOnIndicatorCount:0,confirmedAbnormalCount:0,combinationAnalysis:[],suggestions:[],disclaimer:"请先生成建议草稿。"};return send(res,200,{...data,pptReadySuggestions:(data.suggestions||[]).filter(x=>x.reviewStatus==="已确认")});}
  if(sg && req.method==="PUT"){const d=await projectDir(sg[1]),b=await jsonBody(req),p=JSON.parse(await readFile(join(d,"project.json"))),current=p.suggestions||{},suggestions=Array.isArray(b.suggestions)?b.suggestions.map(x=>({...x,reviewStatus:["待审核","已确认","已修改","需补充","已排除"].includes(x.reviewStatus)?x.reviewStatus:"待审核"})):current.suggestions||[],version={version:(current.versions?.length||0)+1,savedAt:new Date().toISOString(),suggestions:JSON.parse(JSON.stringify(suggestions)),interventionPeriod:String(b.interventionPeriod??current.interventionPeriod??""),reviewPeriod:String(b.reviewPeriod??current.reviewPeriod??"")};p.suggestions={...current,suggestions,interventionPeriod:version.interventionPeriod,reviewPeriod:version.reviewPeriod,versions:[...(current.versions||[]),version],updatedAt:version.savedAt};p.updatedAt=version.savedAt;await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(sg[1],"suggestions.reviewed",{confirmed:suggestions.filter(x=>x.reviewStatus==="已确认").length,total:suggestions.length,version:version.version});return send(res,200,{ok:true,...p.suggestions,pptReadySuggestions:suggestions.filter(x=>x.reviewStatus==="已确认")});}
  const pa=req.url.match(/^\/api\/projects\/([^/]+)\/analyze-all$/); if(pa&&req.method==="POST"){const d=await projectDir(pa[1]),p=JSON.parse(await readFile(join(d,"project.json"))),pdfs=(p.files||[]).filter(file=>file.kind==="pdfs");if(!pdfs.length)return send(res,400,{error:"当前项目没有 PDF"});if(runningProjects.has(pa[1]))return send(res,202,{ok:true,status:"处理中"});analyzeProject(pa[1]).catch(async error=>{const latest=JSON.parse(await readFile(join(d,"project.json")));latest.status="失败";latest.analysisError=error.message;latest.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(latest,null,2));await logAction(pa[1],"analysis.project.failed",{error:error.message})});return send(res,202,{ok:true,status:"处理中",pdfCount:pdfs.length})}
  const ps=req.url.match(/^\/api\/projects\/([^/]+)\/analysis-summary$/); if(ps&&req.method==="GET"){const d=await projectDir(ps[1]),p=JSON.parse(await readFile(join(d,"project.json")));return send(res,200,{status:p.status,files:p.files||[],summary:p.analysisSummary||null,error:p.analysisError||null})}
  const rr=req.url.match(/^\/api\/projects\/([^/]+)\/files\/([^/]+)\/retry$/); if(rr && req.method==="POST"){const id=rr[1],name=decodeURIComponent(rr[2]),d=await projectDir(id),p=JSON.parse(await readFile(join(d,"project.json")));p.files=(p.files||[]).map(f=>f.name===name?{...f,status:"处理中",queueStatus:"queued",retryAt:new Date().toISOString()}:f);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(id,"file.retry",{name});return send(res,200,{ok:true});}
  if (req.method === "POST" && req.url === "/api/analyze") {
    try {
      const body = await jsonBody(req); const localText = String(body.text || ""); const fileName = String(body.fileName || "report.pdf"); const config = body.config || {};
      if(body.projectId){const d=await projectDir(body.projectId),p=JSON.parse(await readFile(join(d,"project.json")));p.files=(p.files||[]).map(f=>f.name===fileName||f.originalName===fileName?{...f,status:"处理中",queueStatus:"processing"}:f);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));}
      if (!localText && !body.pdfBase64) return send(res, 400, { error: "缺少 PDF 内容" });
      let mineru = { text: "", skipped: true }; let mineruError = "";
      try { mineru = await callMinerU(body.pdfBase64, fileName, config.mineru); } catch (error) { mineruError = error.message; }
      const sourceText = mineru.text || localText;
      let ai = null; let aiError = "";
      try { ai = await callDeepSeek(sourceText, fileName, config.deepseek); } catch (error) { aiError = error.message; }
      const reportType=parseReportType(fileName,sourceText);const structuredIndicators=extractStructuredIndicators(mineru.pages||[],fileName,reportType);if(body.projectId){const d=await projectDir(body.projectId),p=JSON.parse(await readFile(join(d,"project.json")));await writeFile(join(d,"parsed",`${safe(fileName)}.json`),JSON.stringify({fileName,reportType,text:sourceText,pages:mineru.pages||[],structuredIndicators,ai,meta:{mineru:!mineru.skipped&&!mineruError,mineruError,deepseek:Boolean(ai),deepseekError:aiError}},null,2));p.files=(p.files||[]).map(f=>f.name===fileName||f.originalName===fileName?{...f,status:mineruError?"失败":"已完成",queueStatus:mineruError?"failed":"completed",parsedAt:new Date().toISOString(),error:mineruError||undefined}:f);p.updatedAt=new Date().toISOString();await writeFile(join(d,"project.json"),JSON.stringify(p,null,2));await logAction(body.projectId,"analysis.saved",{fileName,reportType,indicatorCount:structuredIndicators.length});}
      return send(res, 200, { text: sourceText, ai, meta: { mineru: !mineru.skipped && !mineruError, mineruError, deepseek: Boolean(ai), deepseekError: aiError } });
    } catch (error) { return send(res, 400, { error: error.message || "分析请求失败" }); }
  }
  if(req.method==="POST"&&req.url==="/api/analyze-image"){try{const b=await jsonBody(req),v=await callVision(b.imageBase64,b.fileName||"screenshot.png",b.config?.deepseek||{});if(b.projectId){const d=await projectDir(b.projectId);await writeFile(join(d,"parsed",`${safe(b.fileName||"screenshot")}.vision.json`),JSON.stringify(v,null,2));await logAction(b.projectId,"vision.saved",{fileName:b.fileName})}return send(res,200,v)}catch(e){return send(res,400,{error:e.message})}}
  if (req.method === "POST" && req.url === "/api/test-connection") {
    try { const body = await jsonBody(req); const service = body.service; const cfg = body.config || {}; if (service === "deepseek") { if (!cfg.key) return send(res, 400, { error: "请填写 DeepSeek API Key" }); const base = (cfg.url || "https://api.deepseek.com").replace(/\/$/, ""); const r = await fetch(`${base}/models`, { headers: { Authorization: `Bearer ${cfg.key}` } }); if (!r.ok) throw new Error(`DeepSeek 返回 ${r.status}`); return send(res, 200, { ok: true, message: "DeepSeek 连接成功" }); } if (service === "mineru") { if (!cfg.token) return send(res, 400, { error: "请填写 MinerU Token" }); const r = await fetch(cfg.url || "https://mineru.net", { headers: { Authorization: `Bearer ${cfg.token}` } }); if (!r.ok && r.status !== 404) throw new Error(`MinerU 返回 ${r.status}`); return send(res, 200, { ok: true, message: "MinerU 服务可访问" }); } return send(res, 400, { error: "未知服务" }); } catch (error) { return send(res, 502, { error: error.message || "连接失败" }); }
  }
  const path = req.url === "/" ? "/index.html" : req.url.split("?")[0];
  try { const file = await readFile(join(root, path)); const type = extname(path) === ".html" ? "text/html" : extname(path) === ".css" ? "text/css" : "text/javascript"; res.writeHead(200, { "Content-Type": `${type}; charset=utf-8` }); res.end(file); } catch { res.writeHead(404); res.end("Not found"); }
}
http.createServer((req,res)=>handler(req,res).catch(error=>{console.error(error);if(!res.headersSent)send(res,500,{error:"Internal server error"});else res.destroy()})).listen(port, () => console.log(`医见服务已启动: http://localhost:${port}`));
